on:
  push:
    branches: [ staging, trying, master ]
  pull_request:

name: CI

jobs:
  ci-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # All generated code should be running on stable now
        rust: [stable]

        include:
          # Test MSRV
          - rust: 1.38.0

          # Test nightly but don't fail
          - rust: nightly
            experimental: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Run tests
        run: cargo test --all

# FIXME: test on macOS and Windows
